version: "3"

services:

  scylla-node1:
    container_name: Node1
    image: scylladb/scylla:4.4.0
    restart: always
    command: --smp 1 --memory 750M
    ports:
      - 9042:9042

  scylla-node2:
    container_name: Node2
    image: scylladb/scylla:4.4.0
    restart: always
    command: --seeds=scylla-node1 --smp 1 --memory 750M
    ports:
      - 9043:9043

  scylla-node3:
    container_name: Node3
    image: scylladb/scylla:4.4.0
    restart: always
    command: --seeds=scylla-node1 --smp 1 --memory 750M
    ports:
      - 9045:9045
