micronaut:
  application:
    name: toyProject
  server:
    context-path: /toy/documentation
    cors:
      enabled: true
  router:
    versioning:
      enabled: true
      default-version: 1
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
    endpoints:
      all:
        enabled: true
        sensitive: false
      health:
        enabled: true
        details-visible: ANONYMOUS
      beans:
        enabled: true
      info:
        enabled: true
      routes:
        enabled: true

cassandra:
  default:
    basic:
      contact-points:
        - "172.30.224.1:9042"
      session-keyspace: toy
      load-balancing-policy:
        local-datacenter: datacenter1